// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reserva;

namespace Reserva.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200315143644_tablaReservaciones")]
    partial class tablaReservaciones
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Reserva.Models.Cancha", b =>
                {
                    b.Property<int>("idCancha")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("estado")
                        .HasColumnName("Estado")
                        .HasMaxLength(20);

                    b.Property<int>("idComplejo")
                        .HasColumnName("idComplejo")
                        .HasColumnType("int");

                    b.Property<int>("precio")
                        .HasColumnName("Precio")
                        .HasColumnType("int");

                    b.HasKey("idCancha");

                    b.HasIndex("idComplejo");

                    b.ToTable("Cancha");
                });

            modelBuilder.Entity("Reserva.Models.Complejo", b =>
                {
                    b.Property<int>("idComplejo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cantCanchas")
                        .HasColumnName("CantidadDeCanchas")
                        .HasColumnType("int");

                    b.Property<decimal>("latitud")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Latitud")
                        .HasColumnType("decimal");

                    b.Property<decimal>("longitud")
                        .HasConversion(new ValueConverter<decimal, decimal>(v => default(decimal), v => default(decimal), new ConverterMappingHints(precision: 38, scale: 17)))
                        .HasColumnName("Longitud")
                        .HasColumnType("decimal");

                    b.Property<string>("nombre")
                        .HasColumnName("Nombre")
                        .HasMaxLength(20);

                    b.HasKey("idComplejo");

                    b.ToTable("Complejo");
                });

            modelBuilder.Entity("Reserva.Models.Cancha", b =>
                {
                    b.HasOne("Reserva.Models.Complejo", "complejo")
                        .WithMany()
                        .HasForeignKey("idComplejo")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
